### ISSUE TITLE
Toolchain alignment: Xcode, SDK and Metal versions are selected independently, with no coherence model

### ISSUE THREAD

**Issue by eejd** [eejd/macports-base#76]
## The ask

MacPorts selects the Xcode/`DEVELOPER_DIR`, the SDK, and (on macOS 26+) the Metal toolchain **independently**, maximising or defaulting each axis on its own. There is no model that says which combinations are *coherent*, no validation that the selected combination is one Apple ever shipped, and no way for a Portfile or PortGroup to ask.

The result is that a build can be handed a compiler/header/toolchain tuple that never existed as a shipped configuration, silently, with nothing in the log to say so.

This is the design-level counterpart to #75, which reports one concrete instance (`get_sdkroot` satisfying an Xcode-selected port's SDK request out of the Command Line Tools tree). #75 is the bug; this is the missing model. They should probably be fixed together, because a point fix to `get_sdkroot` will not stop the next axis from drifting.

## Three axes, three *different* constraint shapes

The important finding is that these are not the same rule applied three times. Treating them uniformly is what makes both the over- and under-constrained proposals wrong.

### Metal toolchain ↔ Xcode — equality at `major.minor`

Apple publishes the pairing explicitly, in `~/Library/Developer/Xcode/XcodeToMetalToolchainIndexMapping.plist`, as `xcodeBuildUpdate` → `assetBuildUpdate`. Aggregate over every entry on one host:

```
entries                       : 41
identical build               : 23
same major                    : 41    cross-major:  none
same major.minor (build letter): 41   cross-minor:  none
```

**No entry pairs across a major, and none across a minor.** Only the trailing build suffix ever varies. So this axis has a hard, published, machine-readable invariant — and it is stricter than "same major".

Enforcing it does **not** require that per-user plist (which is the root of the problem the `metal` tooling has under MacPorts, since the `macports` build user does not have one). Two system-wide commands are sufficient:

```console
$ xcodebuild -version
Xcode 26.6
Build version 17F113

$ xcodebuild -json -showComponent MetalToolchain
{ "buildVersion" : "17F109", "status" : "uninstalled" }
```

`showComponent` reports the build Apple pairs with the *active* Xcode, plus whether it is installed. Nothing in base looks at this.

### SDK ↔ compiler — inequality, and the direction is the entire point

Equality would be wrong here, and this is where a naive "align the toolchain" rule does damage. Building against an **older** SDK with a **newer** compiler is the supported mechanism behind deployment targets and cross-OS-version builds; MacPorts depends on it, and it needs no diagnostic.

The unsupported direction is the reverse — **newer SDK headers under an older compiler**. A worked instance from a port tree I maintain: the macOS 27 SDK changed `math.h` to defer `INFINITY`/`NAN` to `<float.h>` through the `__need_infinity_nan` protocol whenever clang modules are enabled (always, for C++20 and later). That protocol exists only in LLVM 22 (llvm/llvm-project#164348) and in Apple clang 21 by cherry-pick. Any toolchain carrying its own LLVM-21-era headers fails outright against that SDK with `use of undeclared identifier 'INFINITY'`.

So the constraint is:

```
SDK major <= compiler major        # NOT ==
```

Backward crossing: permit, silently. Forward crossing a major: this is the case worth failing closed on, because the compiler and the headers were never shipped or tested together.

### Base libraries — transitive, not independent

libc++ and libSystem ship *inside* the SDK, so they are governed by the SDK rule rather than needing one of their own. The single independent lever is `cxx_stdlib`.

## Current state on a real host — an incoherent tuple, chosen silently

| | |
|---|---|
| macOS | 27.0 |
| MacPorts base | 2.12.99 |
| Xcode | 26.6 (`17F113`), clang `2100.1.1.101` |
| CLT | clang `2100.3.33.1` |
| Xcode SDKs | `MacOSX.sdk`, `MacOSX26.sdk`, `MacOSX26.5.sdk` — no 27 |
| CLT SDKs | ...plus `MacOSX27.sdk`, `MacOSX27.0.sdk` |
| `macosx_sdk_version` | `27` (auto: the host major) |
| Metal toolchain | matched build `17F109`, **uninstalled**, no cryptex mounted |

```console
$ ... portlib::configure::get_sdkroot 27 $use_xcode
use_xcode=1 -> /Library/Developer/CommandLineTools/SDKs/MacOSX27.sdk
use_xcode=0 -> /Library/Developer/CommandLineTools/SDKs/MacOSX27.sdk
```

A `use_xcode yes` port therefore builds with `DEVELOPER_DIR` = Xcode 26.6 and `SDKROOT` = the CLT's `MacOSX27.sdk`: **a forward major crossing**, Xcode's `clang-2100.1.1.101` against headers released alongside `clang-2100.3.33.1`. Apple's own clang survives it because of the cherry-pick above; a toolchain with vendored headers does not. The pairing is untested rather than provably broken — which is the complaint. Nothing declared it, so nothing checked it.

Meanwhile the Metal axis is simply absent: the matched component is not installed, and `Xcode.app/.../usr/bin/metal` is a shim that reports

```
error: cannot execute tool 'metal' due to missing Metal Toolchain; use: xcodebuild -downloadComponent MetalToolchain
```

## Where base makes these choices (against `7cd4fa8a3`)

- `src/macports1.0/macports.tcl:1759` — `macosx_sdk_version` defaults to the bare host major, with no check that any installed tree offers it.
- `src/portlib1.0/portlib.tcl:405` — `foreach try_path [list ${sdks_dir} ${cltpath}/SDKs]`: the CLT tree is tried unconditionally in the `use_xcode` branch, with no record that it was used.
- `src/portlib1.0/portlib.tcl:322` — `find_close_sdk` globs `MacOSX${sdk_major}*.sdk`, so it can never fall back *within* a developer dir across a major; the cross-tree jump above is the only escape.
- Nothing anywhere consults the Metal component version.

## What already exists — and is undiscoverable

`src/macports1.0/macports.tcl:45-58` accepts these from `macports.conf` as "config file options with no special handling":

| option | in `macports.conf.default`? |
|---|---|
| `macosx_sdk_version` | **no** |
| `macosx_deployment_target` | **no** |
| `default_compilers` | **no** |
| `cxx_stdlib` | **no** |
| `xcodeversion` | **no** |
| `developer_dir` | yes |
| `build_arch`, `universal_archs` | yes |

Five of the levers that would let an administrator pin the toolchain tuple tree-wide are supported and entirely undocumented in the shipped config template.

## The components ARE parallel-installable — the gap is MacPorts' selection model

It is tempting to conclude that Arch/Debian-style pinning is structurally unavailable here, because Apple's toolchain is not shipped as ports. That conclusion is wrong, and worth refuting explicitly, because it sets the ambition too low.

Every axis can be installed in parallel and selected explicitly, using Apple's own supported tooling:

| axis | parallel install | selection mechanism |
|---|---|---|
| Xcode / Apple clang | multiple `Xcode*.app` side by side | `developer_dir`, `DEVELOPER_DIR`, `xcode-select` |
| macOS SDK | each Xcode carries its own set; additional SDKs can be placed in a `Platforms` tree | `macosx_sdk_version` → `configure.sdkroot` |
| Metal toolchain | **`xcodebuild -downloadComponent MetalToolchain -buildVersion <assetversion> [-exportPath <path>]`** | *(none in base)* |
| MacPorts compilers | `clang-NN` / `llvm-NN` ports | `default_compilers`, `configure.compiler` |

The Metal row is the one that surprised me. Apple's own CLI takes an explicit `-buildVersion`, so a specific Metal toolchain build can be fetched and staged deliberately — and multiple cryptexes can be mounted at once (a state MacPorts PortGroups already have to cope with). The Metal axis is not unpinnable; MacPorts simply has no mechanism that refers to it.

The MacPorts compiler row is already demonstrated in practice — this host carries `clang-20`, `clang-22`, `llvm-20` and `llvm-22` concurrently, with a port tree that standardises on one of them.

So the difference from Debian is **not** capability. It is *redistribution*: MacPorts cannot ship Apple's components as ports, so it cannot fetch the tuple the way `debootstrap` materialises a suite. It must instead **reference locally-installed components, select among them, and validate the combination**.

That is a much smaller gap than "structurally impossible", and it is entirely on MacPorts' side of the line. What is missing is not availability but a model:

- `developer_dir` is a single global with no per-port override and no notion of "the Xcode that actually carries SDK *N*".
- The SDK is requested by version, never by which developer dir should supply it.
- The Metal toolchain has no representation in base at all.
- The five undocumented `macports.conf` pins are per-axis; nothing expresses a *set*.

## Proposal

1. **Model the toolchain as a tuple, not three independent maxima.** `(developer_dir, SDK, Metal toolchain)` resolved and validated together, then any floor applied to the tuple. Selecting the newest value on each axis separately is what produces combinations that never shipped.
2. **Make the tuple declarable, since the components are parallel-installable.** A `macports.conf` toolchain stanza naming the developer dir, SDK and Metal build to use tree-wide — referencing locally-installed components rather than fetching them — with a hard error when a named component is absent or when the named set violates the rules below. This is the closest reachable analogue to pinning a Debian suite, and nothing about Apple's delivery mechanism prevents it.
3. **Give the Metal toolchain a representation in base.** It is currently invisible to MacPorts despite being a required compiler component on macOS 26+, separately versioned, and explicitly fetchable at a chosen build via `xcodebuild -downloadComponent -buildVersion`.
4. **Enforce Metal ↔ Xcode at `major.minor`**, sourced from `xcodebuild -showComponent MetalToolchain`'s `buildVersion` against `xcodebuild -version`, not from a mounted-cryptex glob. Apple's own data says this invariant is exact.
5. **Permit backward SDK crossing silently; refuse or loudly warn on forward major crossing.** Satisfying a request for SDK `N` out of a second tree when the selected `developer_dir` tops out at `N-1` is the specific case that yields an unshipped pairing.
6. **Feasibility-check the requested SDK version.** `macosx_sdk_version` defaulting to the host major is a request nothing may be able to satisfy; choosing the best available SDK explicitly, with a log line, beats arriving there through two layers of silent fallback.
7. **Expose provenance.** A companion to `configure.sdkroot` — e.g. `configure.sdk_developer_dir` — so a Portfile or PortGroup can gate on a mismatch instead of re-deriving it. (A PortGroup of mine tried to re-derive it, scanned both trees, took the maximum, and turned a fail-closed deployment-target gate into one that accepted targets the real SDK could not satisfy. Fixed by reading `configure.sdkroot` — but only because that value is *parseable*, not because provenance is available.)
8. **Document the existing pins** in `macports.conf.default`. A supported tree-wide toolchain pin that nobody can discover is not a feature yet.

## Notes

Filed against this fork for tracking. The analysis is against upstream code at `7cd4fa8a3` ("Move arch and SDK selection to portlib"), the refactor that moved SDK selection into `portlib`, and would be worth forwarding to upstream Trac if the reading holds up.

Deliberately reported using aggregate statistics and released build identifiers only — no beta build numbers or build logs — since macOS 27 is currently a beta seed.
